### ISSUE TITLE
An issue with a task list

### ISSUE THREAD

**Issue by DaisyOlsen** [DaisyOlsen/Daisy-Test#12]
- [ ] Check Theme Files In Due: 6/12/14
 - [ ] Testing @dreamwhisper References #4 
 - [ ] Localization @dreamwhisper 
- [ ] Standards Check @daisyolsen
- [ ] Rainmaker Setup Docs @daisyolsen
- [ ] StudioPress Setup Docs @daisyolsen

| Left-Aligned  | Center Aligned  | Right Aligned |
| :------------ |:---------------:| -----:|
| Check Theme Files | some wordy text | $1600 |
| col 2 is      | centered        |   $12 |
| zebra stripes | are neat        |    $1 |
